plugins:
  - '@semantic-release/github'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/commit-analyzer'
  - - '@semantic-release/changelog'
    - changelogFile: 'Assets/BlackBox/CHANGELOG.md'
  - - '@semantic-release/npm'
    - npmPublish: false,
      pkgRoot: 'Assets/BlackBox'
  - - '@semantic-release/git'
    - assets:
      - 'Assets/BlackBox/package.json'
      - 'Assets/BlackBox/CHANGELOG.md'
